In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [ ]:
#1.1. 
# Muestra las primeras 5 filas del conjunto de datos.

Ejercicios de exploración del conjunto de datos
Muestra las primeras 5 filas del conjunto de datos.

1. Muestra las últimas 5 filas del conjunto de datos.

In [2]:
df = pd.read_csv("world-data-2023_part1.csv", index_col=0)

In [3]:
df.head(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [4]:
df.tail()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

2. Muestra una muestra aleatoria de 5 filas del conjunto de datos.

In [5]:
df.sample(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
29,Cape Verde,138,CV,19.60%,"4,033","1,000",19.49,238.0,Praia,543,110.5,1.10%,CVE,2.27,22.50%,$1.02
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
167,Suriname,4,SR,0.60%,"163,820","2,000",18.54,597.0,Paramaribo,"1,738",294.66,22.00%,SRD,2.42,98.30%,$1.29
9,Austria,109,AT,32.40%,"83,871","21,000",9.70,43.0,Vienna,"61,448",118.06,1.50%,EUR,1.47,46.90%,$1.20
62,The Gambia,239,GM,59.80%,"11,300","1,000",38.54,220.0,Banjul,532,172.73,7.10%,GMD,5.22,48.40%,$1.18

3. Muestra el nombre de todas las columnas en el conjunto de datos.

In [6]:
df.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price'],
      dtype='object')

4. Muestra los valores únicos en la columna "Abbreviation".

In [8]:
df["Abbreviation"].unique

<bound method Series.unique of 0      AF
1      AL
2      DZ
3      AD
4      AO
       ..
190    VE
191    VN
192    YE
193    ZM
194    ZW
Name: Abbreviation, Length: 195, dtype: object>

5. Cuenta cuántas veces aparece cada valor único en la columna "Abbreviation".

In [10]:
df["Abbreviation"].nunique()

188

6. Verifica si hay valores nulos en el conjunto de datos.

In [ ]:
df.isnull() #.isna()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
194,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

7. Verifica si hay valores no nulos en el conjunto de datos.

In [14]:
df.notnull()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,False,True,True,True,True,False,False,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
191,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
192,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
193,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
194,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True

8. Muestra información general sobre el conjunto de datos.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                195 non-null    object
 1   Density
(P/Km2)        195 non-null    object
 2   Abbreviation           188 non-null    object
 3   Agricultural Land( %)  188 non-null    object
 4   Land Area(Km2)         194 non-null    object
 5   Armed Forces size      171 non-null    object
 6   Birth Rate             189 non-null    float64
 7   Calling Code           194 non-null    float64
 8   Capital/Major City     192 non-null    object
 9   Co2-Emissions          188 non-null    object
 10  CPI                    178 non-null    object
 11  CPI Change (%)         179 non-null    object
 12  Currency-Code          180 non-null    object
 13  Fertility Rate         188 non-null    float64
 14  Forested Area (%)      188 non-null    object
 15  Gasoline Price         175 non-null    object
dtypes: float64(3), object(13)
memory usage: 25.9+ KB

9. Elimina una columna específica (por ejemplo, "Armed Forces size").

In [18]:
df.drop(columns = ["Armed Forces size"], inplace=True)

In [19]:
df.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36

10. Selecciona las columnas numéricas del conjunto de datos y muestra sus estadísticas descriptivas básicas (para esto tendréis que usar el método '.describe(), su documentación la tenéis aquí).

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Birth Rate,189.0,20.214974,9.945774,5.90,11.300,17.950,28.7500,46.08
Calling Code,194.0,360.546392,323.236419,1.00,82.500,255.500,506.7500,1876.00
Fertility Rate,188.0,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91

In [21]:
df.describe().count

<bound method DataFrame.count of        Birth Rate  Calling Code  Fertility Rate
count  189.000000    194.000000      188.000000
mean    20.214974    360.546392        2.698138
std      9.945774    323.236419        1.282267
min      5.900000      1.000000        0.980000
25%     11.300000     82.500000        1.705000
50%     17.950000    255.500000        2.245000
75%     28.750000    506.750000        3.597500
max     46.080000   1876.000000        6.910000>

In [22]:
df.describe().min

<bound method DataFrame.min of        Birth Rate  Calling Code  Fertility Rate
count  189.000000    194.000000      188.000000
mean    20.214974    360.546392        2.698138
std      9.945774    323.236419        1.282267
min      5.900000      1.000000        0.980000
25%     11.300000     82.500000        1.705000
50%     17.950000    255.500000        2.245000
75%     28.750000    506.750000        3.597500
max     46.080000   1876.000000        6.910000>

In [23]:
df.describe().max

<bound method DataFrame.max of        Birth Rate  Calling Code  Fertility Rate
count  189.000000    194.000000      188.000000
mean    20.214974    360.546392        2.698138
std      9.945774    323.236419        1.282267
min      5.900000      1.000000        0.980000
25%     11.300000     82.500000        1.705000
50%     17.950000    255.500000        2.245000
75%     28.750000    506.750000        3.597500
max     46.080000   1876.000000        6.910000>